In [3]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

iris=load_iris()
dt_clf=DecisionTreeClassifier()
train_data=iris.data
train_label=iris.target
dt_clf.fit(train_data,train_label)
pred=dt_clf.predict(train_data)
print('예측 정확도 :', accuracy_score(train_label,pred))

예측 정확도 : 1.0

Why 예측 정확도가 100%일까? -> train으로 사용한 데이터 가지고 test 했기 때문이다.
이러면 성능 평가에 어려움이 있다.
그러므로 train data와 test 데이터를 나누어서 진행해야 한다. -> sklearn.model_selection 묘듈에서 train_test_split

train_test_split(feature data set, label data set, test size, train size, shuffle, random_state)
test size : 전체 데이터에서 test 데이터를 얼마 정도 설정할 것인가? 디폴트는 0,25
train size : 전체 데이터에서 train 데이터를 얼마 정도 설정할 것인가? 보통 test size 사용해서 잘 안사용함
shuffle : 데이터를 미리 섞을 것인가? 디폴트는 True
random_state : 무작위로 데이터 분리, 값을 정해주면 돌릴 때마다 같은 값이 나옴.

In [4]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

dt_clf=DecisionTreeClassifier()
iris_data=load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data,iris_data.target,test_size=0.3,random_state=121)

In [5]:
dt_clf.fit(X_train,y_train)
pred=dt_clf.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.9556

train을 시작하기 전에 30%를 test 데이터로 나눴다. 총 150개의 데이터가 있었으므로 105개가 train data, 45개가 test 데이터가 된 것이다.
하지만, 이는 알고리즘의 예측 성능을 판단하기에는 너무 숫자가 적다.
특히 Overfitting (모델이 학습 데이터에만 과도학 최적화되어 실제 예측을 다른 데이터로 수행할 경우에는 예측 성능이 과도하게 떨어짐)에 취약하다.
-> test data에만 최적의 성능을 발휘할 수 있도록 편향되게 모델을 유도하는 경우도 생긴다.

결국, 이러한 데이터 편중을 막기 위해서 교차 검증을 수행한다.

K-Fold Cross Validation : 가장 대표적인 교차 검증 기법
1. 전체 데이터를 K개로 나눈다.
2. 그 중 1개는 test data로, 나머지 K-1개는 train data로 사용한다.
3. 이 과정을 K번 반복하며, 매번 다른 조각을 test data로 사용한다.
4. 그러면 검증을 K번 할 것이다. 마지막에 K번의 평가 결과를 평균내어 최종 성능으로 사용한다.

from sklearn.model_selection import KFold : model_selection 묘듈에서 KFold 클래스를 import 한다.
kfold=KFold(n_splits=5) : 데이터를 5개의 fold로 나눈다.

In [6]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

iris=load_iris()
features=iris.data
label=iris.target
dt_clf=DecisionTreeClassifier(random_state=156)

kfold=KFold(n_splits=5)
cv_accuracy=[]
print('붗꽃 데이터 세트 크기:', features.shape[0])

붗꽃 데이터 세트 크기: 150

In [7]:
# 반복 횟수를 세기 위한 변수 : n_iter
n_iter=0

# kfold.split(features) : feature 데이터를 k개의 fold로 나눠서, train_index와 test_index를 만든다. (index로 출력)
# 여기서 label은 split으로 나누지 않았는데 그 이유는 label은 numpy 데이터라서 train_index 대로 따라가면 되는 것이다.
# 예를 들어, features = np.array([[1], [2], [3], [4], [5]]), label = np.array([0, 0, 1, 1, 1]) 이라고 치면,
# Train: [1 2 3 4] Test: [0] 이렇게 나누어 지고, label은 이 index를 그대로 따라서 가는 것이다.

for train_index, test_index in kfold.split(features):
    X_train, X_test=features[train_index], features[test_index]
    y_train, y_test=label[train_index], label[test_index]

    dt_clf.fit(X_train, y_train)
    pred=dt_clf.predict(X_test)
    n_iter+=1

    accuracy=np.round(accuracy_score(y_test,pred),4)
    train_size=X_train.shape[0]
    test_size=X_test.shape[0]
    print('\n #{0} 교차 검증 정확도 "{1}, 학습 데이터 크기 : {2}, 검증 데이터 크기 : {3}'.format(n_iter,accuracy,train_size, test_size))
    print('\n #{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))
    cv_accuracy.append(accuracy)

print('\n 평균 검증 정확도: ',np.mean(cv_accuracy))

 #1 교차 검증 정확도 "1.0, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30

 #1 검증 세트 인덱스:[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

 #2 교차 검증 정확도 "0.9667, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30

 #2 검증 세트 인덱스:[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

 #3 교차 검증 정확도 "0.8667, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30

 #3 검증 세트 인덱스:[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

 #4 교차 검증 정확도 "0.9333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30

 #4 검증 세트 인덱스:[ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

 #5 교차 검증 정확도 "0.7333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30

 #5 검증 세트 인덱스:[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

 평균 검증 정확도:  0.9

Stratified K-Fold : 특정 label 값이 특이하게 많거나 적은 data에서 클래스 비율을 원본 데이터와 최대한 비슷하가ㅔ 유지.

In [8]:
import pandas as pd

iris=load_iris()
#iris_df : iris.data로 dataframe 생성, 각 열들의 제목은 iris.feature_names(sepal length 등등)
iris_df=pd.DataFrame(data=iris.data,columns=iris.feature_names)
# iris_df에 label열을 추가, 값은 iris.target
iris_df['label']=iris.target
iris_df['label'].value_counts()

label
0    50
1    50
2    50
Name: count, dtype: int64

In [12]:
kfold=KFold(n_splits=3)
n_iter=0

for train_index, test_index in kfold.split(iris_df):
    n_iter+=1
    # label_train = iris_df의 label열의 train_index의 데이터값 (0,1,2중 하나)
    # label_test = iris_df의 label열의 test_index의 데이터값 (0,1,2중 하나)
    label_train=iris_df['label'].iloc[train_index]
    label_test=iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 label
1    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    50
Name: count, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 label
0    50
2    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
1    50
Name: count, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 label
0    50
1    50
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
2    50
Name: count, dtype: int64

위처럼 될 경우 훈련 데이터는 0,1만 50개씩 있는데 테스트 데이터는 2만 50개 있음 -> 2의 데이터는 전혀 학습하지 못함
따라서, 이렇게 될 경우 검증 정확도는 0이 됨
이걸 해결하고자 StratifiedKFold 사용

In [14]:
from sklearn.model_selection import StratifiedKFold

skf=StratifiedKFold(n_splits=3)
n_iter=0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
    n_iter+=1
    label_train=iris_df['label'].iloc[train_index]
    label_test=iris_df['label'].iloc[test_index]
    print('## 교차 검증: {0}'.format(n_iter))
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

## 교차 검증: 1
학습 레이블 데이터 분포:
 label
2    34
0    33
1    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
1    17
2    16
Name: count, dtype: int64
## 교차 검증: 2
학습 레이블 데이터 분포:
 label
1    34
0    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
0    17
2    17
1    16
Name: count, dtype: int64
## 교차 검증: 3
학습 레이블 데이터 분포:
 label
0    34
1    33
2    33
Name: count, dtype: int64
검증 레이블 데이터 분포:
 label
1    17
2    17
0    16
Name: count, dtype: int64

위 경우처럼 하면 0,1,2의 값이 거의 동일하게 나옴

In [18]:
dt_clf=DecisionTreeClassifier(random_state=156)

skfold=StratifiedKFold(n_splits=3)
n_iter=0
cv_accuracy=[]

# StratifiedKFold의 split() 호출 시 반드시 레이블 데이터 세트도 추가 입력 필요 
for train_index, test_index in skfold.split(features,label):
    X_train, X_test=features[train_index], features[test_index]
    y_train, y_test=label[train_index], label[test_index]

    dt_clf.fit(X_train, y_train)
    pred=dt_clf.predict(X_test)

    n_iter+=1
    accuracy=np.round(accuracy_score(y_test,pred),4)
    train_size=X_train.shape[0]
    test_size=X_test.shape[0]
    print('#{0} 교차 검증 정확도:{1}, 학습 데이터 크기 : {2}, 검증 데이터 크기 : {3}'.format(n_iter,accuracy,train_size,test_size))
    print('#{0} 검증 세트 인덱스:{1}'.format(n_iter,test_index))
    cv_accuracy.append(accuracy)

print('## 교차 검증별 정확도:',np.round(cv_accuracy,4))
print('## 평균 검증 정확도 :', np.round(np.mean(cv_accuracy),4))

#1 교차 검증 정확도:0.98, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#1 검증 세트 인덱스:[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
#2 교차 검증 정확도:0.94, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#2 검증 세트 인덱스:[ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]
#3 교차 검증 정확도:0.98, 학습 데이터 크기 : 100, 검증 데이터 크기 : 50
#3 검증 세트 인덱스:[ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]
## 교차 검증별 정확도: [0.98 0.94 0.98]
## 평균 검증 정확도 : 0.9667

원래 교차 검증은 위처럼 code쳐서 해야 하는데, cross_val_score() 이용하면 위 코드 안치고 손쉽게 가능
cross_val_score(estimator, data, label, scoring(무엇을 평가할 것인가),cv(교차 검증 폴드 수))
cross_val+score은 API 내부에서 Estimater을 학습, 예측, 평가까지 모두 시켜주므로 간단하게 교차검증 시행할 수 있움.
또한 기본적으로 StratifiedKFold를 이용함.

cross_validate : 여러 개의 평가 지표 반환 (cross_val_score은 하나의 평가 지표만 반환 가능)

In [19]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data=load_iris()
dt_clf=DecisionTreeClassifier(random_state=156)

data=iris_data.data
label=iris_data.target

scores=cross_val_score(dt_clf,data,label,scoring='accuracy',cv=3)
print('교차 검증별 정확도:', np.round(scores,4))
print('평균 검증 정확도:', np.round(np.mean(scores),4))

교차 검증별 정확도: [0.98 0.94 0.98]
평균 검증 정확도: 0.9667

Hyperparameter : 기계학습 모델을 학습시키기 전에 사용자가 직접 설정해야 하는 값들. 모델의 구조나 학습 방식에 영향을 주며, 학습 과정 중에 자동으로 조정되지 않고 고정된 값으로 사용된다.
학습률(Learning rate): 모델이 얼마나 빠르게 또는 천천히 학습할지를 결정함.
에폭(Epoch): 전체 데이터를 몇 번 반복해서 학습할지를 정함.
배치 크기(Batch size): 한 번에 학습에 사용하는 데이터의 개수.
은닉층 수와 각 층의 뉴런 수: 인공신경망의 구조를 정의하는 값들.
정규화 계수(L2 정규화 등): 과적합을 방지하기 위해 사용하는 규제의 세기.
드롭아웃 비율(Dropout rate): 일부 뉴런을 임의로 끄는 비율로, 일반화 성능 향상에 도움됨.

Hyperparameter는 모델의 성능에 큰 영향을 미치므로, Hyperparamete 튜닝 과정을 통해 최적의 값을 찾아야 한다. 
이때는 그리드 서치(Grid Search), 랜덤 서치(Random Search), 베이지안 최적화(Bayesian Optimization) 등의 기법을 사용할 수 있다.

GridSearchCV :  사이킷런에서 제공하는 하이퍼파라미터 튜닝 도구. 사용자가 지정한 여러 하이퍼파라미터 조합을 체계적으로 탐색하여 최적의 조합을 찾는다.
1. 사용자가 지정한 하이퍼파라미터 후보값들을 조합한다.
2. 각 조합에 대해 Cross Validation을 수행한다.
3. 검증 성능이 가장 좋은 최적의 파라미터 조합과 모델을 반환한다.

In [22]:
grid_parameters = {'max_depth' : [1,2,3],
                   'min_samples_split':[2,3]}
# 이렇게 되면 max_depth=1, min_samples_split=1 / max_depth=1, min_samples_split=2 ....... 이렇게 6번 계산해서 제일 좋은 것을 알려준다.

max_depth, min_samples_split : Decision Tree모델의 대표적인 hyperparameter.
모델의 복잡도와 과적합 여부에 큰 영향을 주는 중요한 요소.

max_depth : 트리가 얼마나 깊게 분기할 수 있나?
너무 깊으면 훈련 데이터에 과도하게 맞춰져서 과적합(overfitting) 위험.
너무 얕으면 데이터의 복잡한 패턴을 놓쳐서 과소적합(underfitting) 가능. 
예를 들어, max_depth가 깊으면 "petal_length가 3.4, petal_width가 1.2여야지 클래스 2" 이렇게 되고 max_depth가 얕으면 "petal length가 2~3, petal_width가 1~2 사이면 클래스 2" 이런 식으로 됨.
따라서 적절한 max_depth 찾는 것이 중요함.

min_samples_split : 노드를 분할하기 위한 최소 샘플 수.
큰 값일수록 덜 분기하므로 트리의 복잡도가 낮아지고 일반화 성능이 좋아질 수 있음.
너무 작으면 노드가 너무 자주 쪼개져서 과적합(overfitting) 위험.
따라서 적절한 min_samples_split 값을 찾는 것도 중요하다.

GridSearchCV(estimator(사용할 모델), param_grid=---(하이퍼파라미터 조합), cv=n(교차검증), scoring='---'(평가 지표), refit=True(최적 모델로 다시 학습))

In [21]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

iris_data=load_iris()
X_train, X_test, y_train, y_test=train_test_split(iris_data.data,iris_data.target,test_size=0.2,random_state=121)

dtree=DecisionTreeClassifier()

parameters={'max_depth':[1,2,3],'min_samples_split':[2,3]}

import pandas as pd

# GridSearchCV (decisiontreeclassifier 모델 사용, max_depth와 min_samples_split 하이퍼파라미터 조합, 3분할 교차검증)
grid_dtree=GridSearchCV(dtree,param_grid=parameters, cv=3, refit=True)

grid_dtree.fit(X_train,y_train)

# cv_results_: GridSearchCV가 내부적으로 계산한 모든 실험 결과를 담고 있는 딕셔너리.
scores_df=pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score','split1_test_score','split2_test_score']]

,params,mean_test_score,rank_test_score,split0_test_score,split1_test_score,split2_test_score
0,"{'max_depth': 1, 'min_samples_split': 2}",0.700000,5,0.700,0.7,0.70
1,"{'max_depth': 1, 'min_samples_split': 3}",0.700000,5,0.700,0.7,0.70
2,"{'max_depth': 2, 'min_samples_split': 2}",0.958333,3,0.925,1.0,0.95
3,"{'max_depth': 2, 'min_samples_split': 3}",0.958333,3,0.925,1.0,0.95
4,"{'max_depth': 3, 'min_samples_split': 2}",0.975000,1,0.975,1.0,0.95
5,"{'max_depth': 3, 'min_samples_split': 3}",0.975000,1,0.975,1.0,0.95

위 결과에서 rank_test_score이 성적이 좋은 순대로 나열함 결과임. 즉, max_depth=3, min_samples_split=2가 가장 좋은 값들임.
grid_dtree.best_params_에는 최고 성능을 나타낸 hypterparameter 값(params), grid_dtree.best_score_에는 이때의 평가 결과가 기록됨.

In [23]:
print('gridSearchCV 최적 파라미터:', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도:{0:.4f}'.format(grid_dtree.best_score_))

gridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도:0.9750

In [25]:
estimator=grid_dtree.best_estimator_

pred=estimator.predict(X_test)
print('테스트 데이터 세트 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

테스트 데이터 세트 정확도: 0.9667

<데이터 전처리>
ML 알고리즘은 데이터에 기반하고 있기 때문에 어떤 데이터를 입력으로 가지느냐에 따라 결과도 크게 달라질 수 있음.

결손값 (NaN,Null)값은 허용되지 않는다. 이 값을 채워 주거나, 드롭해야 한다. (채워 줄지 드롭할지는 결정해야 한다.)

또한, 문자로 된 범주형 변수(categorical variable)는 컴퓨터가 이해 못 한다. 즉, 이 값들을 데이터로 사용하려면 데이터 인코딩 (categorical feature -> 코드형 숫자 값으로 변환)을 해야 한다.

In [27]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print('인코딩 변환값:', labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]

LabelEncoder 클래스 : 문자형 데이터를 정수로 바꿔줌.

fit() : 데이터의 고유한 클래스 목록을 내부적으로 저장하는 단계.
'TV', '냉장고', '전자레인지', '컴퓨터', '선풍기', '믹서'를 알파벳 순으로 정렬해서 매핑을 준비.
즉, TV:0, 냉장고:1, 믹서:2, 선풍기:3, 전자레인지:4, 컴퓨터:5 이렇게 매핑됨.
transform() : 위에서 저장한 매핑을 기준으로 문자형 데이터를 숫자로 변환.

In [28]:
print('인코딩 클래스:', encoder.classes_)
# classes_ 속성 : 0번부터 순서대로 변환된 인코딩 값에 대한 원본값

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']

In [30]:
print('디코딩 원본값:', encoder.inverse_transform([4,5,2,0,1,1,3,3]))
# inverse_transform : 인코딩된 값을 다시 디코딩

디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']

<One-Hot Encoding>

feature 값의 유형에 따라 새로운 feature을 추가해 고유 값에 해당하는 열에만 1을 표시, 나머지는 0을 표시.

주의할 점은, 입력값으로 2차원 데이터가 필요하고, OneHotEncoder를 이용해 변환한 값이 희소 행렬(Sparse Matrix) 형태이므로 이를 다시 toarray() 메서드를 이용해 밀집행렬(Dense Matrix)로 변환해야 함.

OneHotEncoder : 범주형 데이터를 0과 1로 이루어진 벡터로 바꿔주는 인코더
sparse matrix : 아래의 꼴로 나타남 (0행 2열에 1 저장....) -> 기본적으로 OneHotEncoder를 적용하면 0이 많이 표시되기 때문에 효율적인 저장을 위해서
(0, 2)	1.0
(1, 0)	1.0
(2, 1)	1.0
Dense Matrix : 우리가 기본적으로 아는 행렬
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]

In [33]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

# 2차원 ndarray로 변환.
items=np.array(items).reshape(-1,1)

# OneHotEncoding 적용
oh_encoder=OneHotEncoder()
oh_encoder.fit(items)
oh_labels=oh_encoder.transform(items)

# OneHotEncoder로 변환한 결과는 sparse matrix이므로 이를 dense matrix으로 변환
print('OneHotEncoding data')
print(oh_labels.toarray())
print('OneHotEncoding data 차원')
print(oh_labels.shape)

OneHotEncoding data
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
OneHotEncoding data 차원
(8, 6)

pandas에는 OneHotEncoding을 쉽게 지원하는 API 존재 -> get_dummies()

In [35]:
import pandas as pd

df=pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df,dtype=int)

   item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

<Feature Scaling>
모델 성능을 높이기 위해 서로 다른 스케일을 가진 데이터를 일정한 범위로 맞춰주는 과정.

1. 표준화(Standardization) : 데이터를 평균 0, 표준편차 1이 되도록 바꿈. 평균과 분산에 따라 상대적인 위치를 보여줌.
x_new=(x-평균)/표준편차
사이킷런에서 StandardScaler 클래스에서 사용.

2. 정규화(Nomalization) : 데이터의 크기를 0~1로 바꾸는 방법. 데이터 분포가 정규분포가 아닌 경우에 적용.
x_new=(x-최솟값)/(최댓값-최솟값)
사이킷런에서 MinMaxScaler 클래스에서 사용.

3. 벡터 정규화 (Vector Nomalization) : 앞서 말한 정규화는 보통 Min-Max 정규화를 의미함. 그러나 거리 기반 알고리즘(KNN 등)에서는 벡터 정규화를 사용.
x_new=x/모든 벡터의 길이(유클리디안 거리)
사이킷런에서 Normalizer 클래스에서 사용.

In [36]:
from sklearn.datasets import load_iris
import pandas as pd

iris=load_iris()
iris_data=iris.data
iris_df=pd.DataFrame(data=iris_data,columns=iris.feature_names)

print('feature 들의 평균 값')
print(iris_df.mean())
print('\n feature 들의 분산 값')
print(iris_df.var())
# 분산 : var() 메서드 사용

feature 들의 평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64

 feature 들의 분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64

In [38]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)

iris_df_scaled=pd.DataFrame(data=iris_scaled,columns=iris.feature_names)
print('feature 들의 평균 값')
print(iris_df_scaled.mean())
print('\n feature 들의 분산 값')
print(iris_df_scaled.var())

feature 들의 평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64

 feature 들의 분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64

In [41]:
from sklearn.preprocessing import MinMaxScaler

scaler=MinMaxScaler()
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)

iris_df_scaled=pd.DataFrame(data=iris_scaled,columns=iris.feature_names)
print('feature 들의 최솟값')
print(iris_df_scaled.min())
print('\n feature 들의 최댓값')
print(iris_df_scaled.max())

feature 들의 최솟값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64

 feature 들의 최댓값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64

In [43]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# 학습 데이터는 0부터 10까지, 테스트 데이터는 0부터 5까지 값을 가지는 데이터 세트로 생성
# Scaler 클래스의 fit(), transform()은 2차원 이상 데이터만 가능하므로 reshape(-1,1)로 차원 변경
train_array=np.arange(0,11).reshape(-1,1)
test_array=np.arange(0,6).reshape(-1,1)

# MinMaxScaler 객체에 별도의 feature_range 파라미터 값을 지정하지 않으면 0~1의 값으로 변환.
scaler=MinMaxScaler()

# fit() 하게 되면 train_array 데이터의 최솟값이 0, 최댓값이 10으로 설정
scaler.fit(train_array)

# 1/10 scale로 train_array 데이터 변환함. 원본 10->1로 변환됨.
train_scaled=scaler.transform(train_array)

print('원본 train_array 데이터:', np.round(train_array.reshape(-1),2))
print('scale된 train_array 데이터:', np.round(train_scaled.reshape(-1),2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]

In [44]:
# fit() 하게 되면 test_array 데이터의 최솟값이 0, 최댓값이 5로 설정
scaler.fit(test_array)

# 1/5 scale로 test_array 데이터 변환함. 원본 5->1로 변환됨.
test_scaled=scaler.transform(test_array)

print('원본 test_array 데이터:', np.round(test_array.reshape(-1),2))
print('scale된 test_array 데이터:', np.round(test_scaled.reshape(-1),2))

원본 test_array 데이터: [0 1 2 3 4 5]
scale된 test_array 데이터: [0.  0.2 0.4 0.6 0.8 1. ]

위에서 train_scaled에서는 1이 0.1로 변환되었고, test_scaled에서는 1이 0.2로 변환되었음.
test 데이터의 scaling은 train 데이터를 따라야 하기에, 위 변환은 잘못됨.
따라서, test 데이터의 scaling을 진행할 때에는 train 데이터로 fit된 scaler를 사용해야 함.

In [45]:
scaler=MinMaxScaler()
scaler.fit(train_array)
train_scaled=scaler.transform(train_array)
print('원본 train_array 데이터:', np.round(train_array.reshape(-1),2))
print('scale된 train_array 데이터:', np.round(train_scaled.reshape(-1),2))

test_scaled=scaler.transform(test_array)
print('원본 test_array 데이터:', np.round(test_array.reshape(-1),2))
print('scale된 test_array 데이터:', np.round(test_scaled.reshape(-1),2))

원본 train_array 데이터: [ 0  1  2  3  4  5  6  7  8  9 10]
scale된 train_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
원본 test_array 데이터: [0 1 2 3 4 5]
scale된 test_array 데이터: [0.  0.1 0.2 0.3 0.4 0.5]